gems:
    - jekyll-assets
    - jekyll-sitemap

exclude: ['Gemfile', 'Gemfile.lock', 'README.md', 'css', 'js', 'config.ru', 'vendor']

sass:
  sass_dir: css/_scss

assets:
  compress:
    css: default
    js: default

  autowrite: true

  assets:
    - 'main.css'
    - '*.js'

  sources:
    - css
    - js

# ------------------------

# Build settings
markdown: kramdown

# Texts

main:
  title: 'WAM'
  subtitle: 'Lorem ipsum'
  description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.'
  keysellingpoint: 'Key Selling Point'
  cta: 'This is a CTA'
  sectionsubtitle: 'This is a subtitle'
  sectiontitle: 'This is a title'
  product: 'Product'
  longdescription: 'This is a long description related to the product. Lorem ipsum dolor sit amet.'
  
header:
  link: 'LINK'
  
footer:
  link: 'LINK'
  telephone1: 'FREE CALL TO OUR'
  telephone2: 'TELEPHONE'
  conditions: 'TERMS & CONDITIONS'
  cookies: 'COOKIE POLICIE'
  terms: 'LEGAL TERMS'
  policy: 'PRIVACY POLICY'
  copyright: 'COPYRIGHT © 2022 COMPANY. ALL RIGHTS RESERVED'
